linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  # gci:
  #   local-prefixes: insert your package name here
  # goimports:
  #   local-prefixes: insert your package name here
  golint:
    min-confidence: 0
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: false # too many false positives when shadowing errors
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - goerr113
    - prealloc

  # don't enable:
  # - asciicheck
  # - errcheck # Disabled since it detects defers that do not check errors. This is a standard pattern.
  #              see https://github.com/kisielk/errcheck/issues/55
  # - scopelint
  # - gocognit
  # - godot
  # - godox
  # - interfacer
  # - nestif
  # - testpackage
  # - golint # deprecated
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # config folder and embed.go only contain globals
    - path: config/|embed(_gen)?\.go
      linters:
        - gochecknoglobals
        - lll
    - path: pkg/gotemplate/options\.go
      linters:
        # numbers used for options that support multiple options
        - gomnd
    - path: _test\.go
      linters:
        - gomnd
        - gochecknoglobals
        - gosec
        - noctx
        - goerr113
        - funlen
        - goconst
    # only small tools that use globals for templating
    # and errors for CLI error output
    - path: (dotembed|options2md)\/main\.go
      linters:
        - gochecknoglobals
        - goerr113

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
