linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam # TODO maybe pass all by pointer?
      - rangeValCopy # TODO fix in the future maybe
      - sloppyReassign # TODO fix in the future maybe
  gocyclo:
    min-complexity: 30 # decrease this
      # gci:
      #   local-prefixes: insert your package name here
      # goimports:
      #   local-prefixes: insert your package name here
      #revive:
      #rules:
      #- name: var-naming
    #severity: warning
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: true # require nolint directives to be specific about which linter is being skipped
  stylecheck:
    # ST1003 underscore in package names and var-naming
    checks: ["all", "-ST1003"]

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc

  # don't enable:
  # - funlen # TODO reconcile functions are way too large
  # - revive # TODO disable underscore in package name
  # - gomnd # magic number detected -> sometimes useful
  # - golint # is deprecated
  # - goerr113 # we have some dynamic errors
  # - exhaustive # missing switch case statements
  # - asciicheck
  # - errcheck # Disabled since it detects defers that do not check errors. This is a standard pattern.
  #              see https://github.com/kisielk/errcheck/issues/55
  # - scopelint
  # - gochecknoinits
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - interfacer
  # - nestif
  # - testpackage
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gochecknoglobals
        - gosec
        - noctx
        - goerr113
        - goconst
        - dupl

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
