project_name: gt

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

before:
  hooks:
    - go mod tidy

dist: bin

builds:
  - id: gt
    env:
      - CGO_ENABLED=0
    main: ./cmd/gt
    ldflags:
      - -s
      - -w
      - -extldflags '-static'
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64

source:
  enabled: true

checksum:
  name_template: 'checksums.txt'

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
