project_name: gt

snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'

before:
  hooks:
    - go mod tidy

dist: bin

builds:
  - id: gt
    env:
      - CGO_ENABLED=0
    main: ./cmd/gt
    ldflags:
      - -s
      - -w
      - -extldflags '-static'
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64

source:
  enabled: true

sboms:
  - artifacts: binary
  - id: source
    artifacts: source

checksum:
  name_template: 'checksums.txt'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true

archives:
  - format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
