// Code generated by dotembed. DO NOT EDIT.
	package gotemplate

	import "embed"

	//go:embed _template _template/.azure-pipelines.yml _template/.dockerignore _template/.editorconfig _template/.githooks _template/.github _template/.gitignore _template/.gitlab-ci.yml _template/.golangci.yml _template/.hadolint.yml
	var FS embed.FS
	