---
# based on https://github.com/marketplace/actions/hadolint-action
name: Hadloint

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hadolint:
    name: Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          config: ./.hadolint.yaml
          dockerfile: ./Dockerfile
