name: Generate files

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "config/version.txt"
      - "README.md"

jobs:
  generate:
    permissions:
      contents: write   

    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.21.6"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.SIT_BOT_PAT }}
          fetch-depth: 0

      - name: Run generate
        if: matrix.os == 'ubuntu-latest'
        run: make generate

      - name: Check for file changes
        id: git-check
        if: matrix.os == 'ubuntu-latest'
        run: echo "changed=$(if git diff --quiet; then echo 'false'; else echo 'true'; fi)" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "opensource@mail.schwarz"
          git config --local user.name "SchwarzIT Bot"
          # This is more robust. It adds ALL files modified by 'make generate'.
          git add .
          git commit -m "chore: regenerate files"

      - name: Push changes
        if: steps.git-check.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SIT_BOT_PAT }}
          branch: main
