name: Semgrep

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "config/version.txt"
      - "README.md"
      - "nix/**"

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/auto
          generateSarif: "1"

      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@7df0ce34898d659f95c0c4a09eaa8d4e32ee64db # v2.2.12
        with:
          sarif_file: semgrep.sarif
        if: always()
