name: Semgrep

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "config/version.txt"
      - "README.md"
      - "nix/**"

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/auto
          generateSarif: "1"

      # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
        with:
          sarif_file: semgrep.sarif
        if: always()
